"""Added Tool Records model

Revision ID: 39853c915583
Revises: 8276c233e878
Create Date: 2024-09-19 22:29:38.301189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39853c915583'
down_revision: Union[str, None] = '8276c233e878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolrecords',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('store_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_toolrecords_employee_id_employees')),
    sa.ForeignKeyConstraint(['store_employee_id'], ['store_employees.id'], name=op.f('fk_toolrecords_store_employee_id_store_employees')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_toolrecords_tool_id_tools')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toolrecords')
    # ### end Alembic commands ###
